name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_FORCE_RUBY_PLATFORM: 1
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5", "2.6", "2.7", "truffleruby"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: /home/runner/bundle
        key: bundle-${{ matrix.ruby }}-${{ hashFiles('**/*.gemspec') }}-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          bundle-${{ matrix.ruby }}-
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle install
      run: |
        bundle config path /home/runner/bundle
        bundle config --global gemfile ${{ matrix.gemfile }}
        bundle install
        bundle update
    - name: Run RSpec
      run: |
        bundle exec rspec
